### ISSUE TITLE
request: include rewards for trading

### ISSUE THREAD

**Issue by Viterbo** [vapaee/vapaee-smart-contracts#21]
**type:**
feature request

**problem:**
Already exist a way to reward users who help with the maintenance process, but these rewards are not used in the rest of the system. It would be nice to have those rewards also when trading as we normally do.

**solution:**
Each time a deal is made, both traders (seller and buyer) should get points and experience based on the volume traded. 

**code:**
This is the function [aux_generate_sell_order](https://github.com/vapaee/vapaee-smart-contracts/blob/telosbookdex/include/vapaee/dex/modules/exchange.hpp#L266) in which this solution should be implemented. On each deal, a traded volume is calculated. That volume should be multiplicated by a constant to determine the final reward for the traders.

The [action_reward_user](https://github.com/vapaee/vapaee-smart-contracts/blob/telosbookdex/include/vapaee/dex/modules/experience.hpp#L40) already exists and, as an example, it is being used here to [send a reward action](https://github.com/vapaee/vapaee-smart-contracts/blob/telosbookdex/include/vapaee/dex/modules/maintenance.hpp#L360) to the user

**Comment by guilledk** [comment]
So checking out the code turns out thats already in! 

[This](https://github.com/vapaee/vapaee-smart-contracts/blob/5757d33b703b88eff0d0f32ad3e6966169661687/include/vapaee/dex/modules/exchange.hpp#L216) helper function calculates the rewards for the maker and taker, and [here](https://github.com/vapaee/vapaee-smart-contracts/blob/5757d33b703b88eff0d0f32ad3e6966169661687/include/vapaee/dex/modules/exchange.hpp#L537) it is used.
